services:
  flb:
    image: 007gzs/flb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/flb/data
    ports:
      - "80:80"
      - "43:443"
      - "127.0.0.1:9000:9000"
    restart: unless-stopped

