/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/certs': RouteRecordInfo<'/certs', '/certs', Record<never, never>, Record<never, never>>,
    '/dns': RouteRecordInfo<'/dns', '/dns', Record<never, never>, Record<never, never>>,
    '/domains': RouteRecordInfo<'/domains', '/domains', Record<never, never>, Record<never, never>>,
    '/hosts': RouteRecordInfo<'/hosts', '/hosts', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/upstreams': RouteRecordInfo<'/upstreams', '/upstreams', Record<never, never>, Record<never, never>>,
  }
}
